version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
      time: "06:00"
    assignees:
      - "andyone"
    reviewers:
      - "andyone"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
