[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "pkg.re/check.v1"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v11"
  version = "11.3.1"

[prune]
  go-tests = true
  unused-packages = true
