[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/fasthttp"

[[constraint]]
  branch = "master"
  name = "pkg.re/check.v1"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v10"
  version = "10.11.0"

[[constraint]]
  name = "pkg.re/essentialkaos/librato.v8"
  version = "8.0.0"

[prune]
  go-tests = true
  unused-packages = true
