[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "1.27.0"

[[constraint]]
  name = "pkg.re/essentialkaos/check.v1"
  version = "1.0.0"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v12"
  version = "12.20.4"

[prune]
  go-tests = true
  unused-packages = true
