[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "1.18.0"

[[constraint]]
  branch = "master"
  name = "pkg.re/check.v1"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v12"
  version = "12.11.0"

[prune]
  go-tests = true
  unused-packages = true
