########################################################################################

# This Makefile generated by GoMakeGen 0.5.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt all clean deps

########################################################################################

all: morpher-librato morpher-server

morpher-librato:
	go build morpher-librato.go

morpher-server:
	go build morpher-server.go

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v github.com/valyala/fasthttp
	go get -d -v pkg.re/essentialkaos/ek.v8
	go get -d -v pkg.re/essentialkaos/librato.v6

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

clean:
	rm -f morpher-librato
	rm -f morpher-server

########################################################################################
